/**
 * Product brand identifiers for Shift.
 * Keep env / HTTP / meta names here so renames stay in one place.
 */
const PRODUCT_NAME = "Shift";
const PRODUCT_TAGLINE_ZH = "交班台";
const PRODUCT_DISPLAY = `${PRODUCT_NAME} · ${PRODUCT_TAGLINE_ZH}`;

const UI_TOKEN_HEADER = "x-shift-ui-token";
const UI_TOKEN_HEADER_CANONICAL = "X-Shift-UI-Token";
const UI_TOKEN_META = "shift-ui-token";
const UI_TOKEN_PLACEHOLDER = "__SHIFT_UI_TOKEN__";

const LOCAL_STATE_DIR = ".shift";

const ENV = Object.freeze({
  UI_TOKEN: "SHIFT_UI_TOKEN",
  API_URL: "SHIFT_API_URL",
  TOKEN_TTL_MS: "SHIFT_TOKEN_TTL_MS",
  TRANSCRIPT_DIR: "SHIFT_TRANSCRIPT_DIR",
  AUDIT_TRANSCRIPT_DIR: "SHIFT_AUDIT_TRANSCRIPT_DIR",
  TEST_CAPACITY: "SHIFT_TEST_CAPACITY",
  PREVIEW: "SHIFT_PREVIEW",
  STORAGE_MODE: "SHIFT_STORAGE_MODE",
  AUDIT_TRANSCRIPT: "SHIFT_AUDIT_TRANSCRIPT",
  MEMORY_DB: "SHIFT_MEMORY_DB",
  RETRIEVE_BUDGET_CHARS: "SHIFT_RETRIEVE_BUDGET_CHARS",
  RETRIEVE_A2A_BUDGET_CHARS: "SHIFT_RETRIEVE_A2A_BUDGET_CHARS",
  RETRIEVE_RECENT_LIMIT: "SHIFT_RETRIEVE_RECENT_LIMIT",
  RETRIEVE_RELATED_LIMIT: "SHIFT_RETRIEVE_RELATED_LIMIT",
  RETRIEVE_ALWAYS_ON_BUDGET_CHARS: "SHIFT_RETRIEVE_ALWAYS_ON_BUDGET_CHARS",
  SEARCH_MEMORY_QUOTA: "SHIFT_SEARCH_MEMORY_QUOTA",
  SEARCH_MESSAGE_QUOTA: "SHIFT_SEARCH_MESSAGE_QUOTA",
  SEARCH_INCLUDE_THINKING: "SHIFT_SEARCH_INCLUDE_THINKING",
  HANDOFF_POLICY: "SHIFT_HANDOFF_POLICY",
  MEMORY_METRICS_LOG: "SHIFT_MEMORY_METRICS_LOG",
  THREAD_ID: "SHIFT_THREAD_ID",
  INVOCATION_ID: "SHIFT_INVOCATION_ID",
  CALLBACK_TOKEN: "SHIFT_CALLBACK_TOKEN",
  WORKTREE: "SHIFT_WORKTREE",
  BASE_DIR: "SHIFT_BASE_DIR",
  WORKTREE_DIR: "SHIFT_WORKTREE_DIR",
  BRANCH: "SHIFT_BRANCH",
  GROK_IMPLEMENTATION_GATE: "SHIFT_GROK_IMPLEMENTATION_GATE",
  GROK_APPROVED_PLAN_HASH: "SHIFT_GROK_APPROVED_PLAN_HASH",
  SESSION_ID: "SHIFT_SESSION_ID",
  RUNTIME_ROOT: "SHIFT_RUNTIME_ROOT",
});

module.exports = {
  PRODUCT_NAME,
  PRODUCT_TAGLINE_ZH,
  PRODUCT_DISPLAY,
  UI_TOKEN_HEADER,
  UI_TOKEN_HEADER_CANONICAL,
  UI_TOKEN_META,
  UI_TOKEN_PLACEHOLDER,
  LOCAL_STATE_DIR,
  ENV,
};
